example/urls.py
from django.urls import path

from example.views import OrderListView, OrderCreateView, OrderUpdateView

app_name = 'example'
urlpatterns = [
    path('', OrderListView.as_view(), name='orders'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update'),
]

inlineformset/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example.urls')),
]

example/models.py
from datetime import date

from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=150)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.CharField(max_length=150)
    date = models.DateField(default=date.today, editable=False)

    def __str__(self):
        return "{}'s order".format(self.customer)


class OrderedItem(models.Model):
    order = models.ForeignKey(Order, related_name='ordered_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='orders', on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()

    def __str__(self):
        return "{} ({})".format(self.product, self.quantity)

example/forms.py
from crispy_forms.layout import Submit, Layout, Div, Field, Fieldset, HTML, ButtonHolder
from django.forms import models, inlineformset_factory
from crispy_forms.helper import FormHelper

from example.custom_layout_object import Formset
from example.models import Order, OrderedItem


class OrderForm(models.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.html5_required = True
        self.helper.form_show_labels = True
        self.helper.layout = Layout(
            Div(
                Field('customer'),
                Fieldset('Items',
                         Formset('items_formset')),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'Save')),
            )
        )


class OrderedItemForm(models.ModelForm):
    class Meta:
        model = OrderedItem
        fields = '__all__'


OrderedItemFormSet = inlineformset_factory(Order, OrderedItem, OrderedItemForm, max_num=5, min_num=1,
                                           validate_min=True, extra=1)

example/views.py
from django.db import transaction
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from example.forms import OrderedItemFormSet, OrderForm
from example.models import Order


class OrderListView(ListView):
    template_name = 'example/orders.html'
    queryset = Order.objects.all()


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('example:orders')
    template_name = 'example/create.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['items_formset'] = OrderedItemFormSet(self.request.POST, prefix='items')
        else:
            data['items_formset'] = OrderedItemFormSet(prefix='items')
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        items = context['items_formset']
        with transaction.atomic():
            self.object = form.save()
            if items.is_valid():
                items.instance = self.object
                items.save()
            else:
                return render(self.request, self.template_name,
                              {"form": self.form_class(self.request.POST), "items_formset": items, })

        return super().form_valid(form)


class OrderUpdateView(UpdateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('example:orders')
    template_name = 'example/update.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        print(self.object)
        if self.request.POST:
            data['items_formset'] = OrderedItemFormSet(self.request.POST, instance=self.object, prefix='items')
        else:
            data['items_formset'] = OrderedItemFormSet(instance=self.object, prefix='items')
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        items = context['items_formset']
        with transaction.atomic():
            self.object = form.save()
            if items.is_valid():
                items.instance = self.object
                items.save()
            else:
                return render(self.request, self.template_name,
                              {"form": self.form_class(self.request.POST), "items_formset": items, })

        return super().form_valid(form)

example/templates/example/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      {% crispy form %}
    </div>
  </div>
{% endblock %}

example/templates/example/formset.html
{% load crispy_forms_tags %}
{% load staticfiles %}
<table class="col-md-9" style="margin-left: 10px;">
  {{ formset.management_form|crispy }}

  {% for form in formset.forms %}
    <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
      {% for field in form.visible_fields %}
        <td>
          {# Include the hidden fields in the form #}
          {% if forloop.first %}
            {% for hidden in form.hidden_fields %}
              {{ hidden }}
            {% endfor %}
          {% endif %}
          {{ field.errors.as_ul }}
          {{ field|as_crispy_field }}
        </td>
      {% endfor %}
    </tr>
  {% endfor %}

</table>
<br>
<script src="{% static 'vendor/jquery-slim.min.js' %}"></script>
<script src="{% static 'example/libraries/django-dynamic-formset/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

example/templates/example/orders.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <p>
        <a href="{% url 'example:create' %}" class="btn btn-info">Create order</a>
      </p>
      <h1>Orders</h1>
      {% for order in object_list %}
        <ul class="list-group">
          <a href="javascript:" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">{{ order.customer }}</h5>
              <small>{{ order.date }}</small>
            </div>
            <ul class="list-group list-group-flush">
              {% for item in order.ordered_items.all %}
                <li class="list-group-item">
                  {{ item.product }} <span class="badge badge-primary badge-pill">{{ item.quantity }}</span>
                </li>
              {% endfor %}
            </ul>
          </a>
          <a href="{% url 'example:update' order.id %}" class="btn btn-secondary" role="button">Edit</a>
        </ul>
        <br>
      {% endfor %}
    </div>
  </div>
{% endblock %}

example/templates/example/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      {% crispy form %}
    </div>
  </div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>inlineformset</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="javascript:">inlineformset</a>
</nav>

<main role="main" class="container">
  <div class="starter-template">
    {% block content %}{% endblock %}
  </div>
</main><!-- /.container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'vendor/jquery-slim.min.js' %}"></script>
<script src="{% static 'vendor/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>